# Auto-generated from legacy config/default_config.json.
# Runtime configuration is stored in the database table config_kv.
# This module is only a bootstrap seed for fresh databases and does not persist changes.

DEFAULT_CONFIG_SEED = {'jump_hosts': [{'name': 'default-jump',
                 'host': '10.0.0.1',
                 'port': 22,
                 'user': 'root',
                 'key': '~/.ssh/id_rsa',
                 'key_content': None,
                 'password': None}],
 'servers': [{'name': 'prod-1',
              'host': '192.168.1.100',
              'port': 22,
              'user': 'root',
              'key': '~/.ssh/id_rsa',
              'key_content': None,
              'password': None,
              'jump_host': 'default-jump'},
             {'name': 'pak-tecx',
              'host': 'pak-tecx',
              'port': 22,
              'user': 'root',
              'key': '~/.ssh/id_rsa',
              'key_content': None,
              'password': None},
             {'name': 'tha-aliyun',
              'host': 'iZ0joebxx83mcmmdm41c2fZ',
              'port': 22,
              'user': 'root',
              'key': '~/.ssh/id_rsa',
              'key_content': None,
              'password': None},
             {'name': 'idn-1xbet',
              'host': 'idn-1xbet',
              'port': 22,
              'user': 'root',
              'key': '~/.ssh/id_rsa',
              'key_content': None,
              'password': None},
             {'name': 'bgd-server',
              'host': 'bgd-server',
              'port': 22,
              'user': 'root',
              'key': '~/.ssh/id_rsa',
              'key_content': None,
              'password': None}],
 'systems': {'buoy': {'display_name': 'Buoy 浮标',
                      'servers': ['prod-1'],
                      'services': [{'name': 'buoy-frontend',
                                    'display_name': '前端',
                                    'template': 'generic_frontend',
                                    'servers': ['prod-1'],
                                    'template_variables': {'deploy_path': '/data/www', 'update_script': './www.sh'}},
                                   {'name': 'buoy-core',
                                    'display_name': 'Core 端',
                                    'template': 'generic_backend_bluegreen',
                                    'servers': ['prod-1'],
                                    'template_variables': {'service_dir': '/data/bin/buoy/core',
                                                           'service_name': 'core',
                                                           'pm2_name': 'core',
                                                           'caddy_config': '/etc/caddy/buoy.conf',
                                                           'caddy_old_port': '8080',
                                                           'caddy_new_port': '8081'}},
                                   {'name': 'buoy-order',
                                    'display_name': 'Order 端',
                                    'template': 'generic_backend_direct',
                                    'servers': ['prod-1'],
                                    'template_variables': {'service_dir': '/data/bin/buoy/order1',
                                                           'service_name': 'order',
                                                           'update_script': 'pm2 restart order',
                                                           'pm2_name': 'order'}},
                                   {'name': 'buoy-module',
                                    'display_name': 'Module 端',
                                    'template': 'generic_backend_direct',
                                    'servers': ['prod-1'],
                                    'template_variables': {'service_dir': '/data/bin/buoy/module1.2',
                                                           'service_name': 'module',
                                                           'update_script': 'pm2 restart module',
                                                           'pm2_name': 'module'}}]},
             'crypto-trader': {'display_name': 'Crypto Trader 量化',
                               'servers': ['prod-1'],
                               'services': [{'name': 'crypto-frontend',
                                             'display_name': '前端',
                                             'template': 'generic_frontend',
                                             'servers': ['prod-1'],
                                             'template_variables': {'deploy_path': '/data/www',
                                                                    'update_script': './www.sh',
                                                                    'server_keywords': ['frontend',
                                                                                        'frontend',
                                                                                        'web',
                                                                                        'www',
                                                                                        '前端'],
                                                                    'servers_by_env': {}}},
                                            {'name': 'crypto-exchange',
                                             'display_name': 'Exchange',
                                             'template': 'generic_backend_direct',
                                             'servers': ['prod-1'],
                                             'template_variables': {'service_dir': '/data/bin/crypto-trader/exchange',
                                                                    'service_name': 'exchange',
                                                                    'update_script': './updatebin.sh',
                                                                    'pm2_name': 'exchange',
                                                                    'server_keywords': ['exchange'],
                                                                    'servers_by_env': {}}},
                                            {'name': 'crypto-monitor',
                                             'display_name': 'Monitor',
                                             'template': 'generic_backend_direct',
                                             'servers': ['prod-1'],
                                             'template_variables': {'service_dir': '/data/bin/crypto-trader/monitor',
                                                                    'service_name': 'monitor',
                                                                    'update_script': './updatebin.sh',
                                                                    'pm2_name': 'monitor',
                                                                    'server_keywords': ['monitor'],
                                                                    'servers_by_env': {}}},
                                            {'name': 'crypto-puller',
                                             'display_name': 'Puller',
                                             'template': 'generic_backend_direct',
                                             'servers': ['prod-1'],
                                             'template_variables': {'service_dir': '/data/bin/crypto-trader/puller',
                                                                    'service_name': 'puller',
                                                                    'update_script': './updatebin.sh',
                                                                    'pm2_name': 'puller',
                                                                    'server_keywords': ['puller'],
                                                                    'servers_by_env': {}}},
                                            {'name': 'crypto-risk',
                                             'display_name': 'Risk',
                                             'template': 'generic_backend_direct',
                                             'servers': ['prod-1'],
                                             'template_variables': {'service_dir': '/data/bin/crypto-trader/risk',
                                                                    'service_name': 'risk',
                                                                    'update_script': './updatebin.sh',
                                                                    'pm2_name': 'risk',
                                                                    'server_keywords': ['risk'],
                                                                    'servers_by_env': {}}},
                                            {'name': 'crypto-sender',
                                             'display_name': 'Sender',
                                             'template': 'generic_backend_direct',
                                             'servers': ['prod-1'],
                                             'template_variables': {'service_dir': '/data/bin/crypto-trader/sender',
                                                                    'service_name': 'sender',
                                                                    'update_script': './updatebin.sh',
                                                                    'pm2_name': 'sender',
                                                                    'server_keywords': ['sender'],
                                                                    'servers_by_env': {}}},
                                            {'name': 'crypto-strategy',
                                             'display_name': 'Strategy',
                                             'template': 'generic_backend_direct',
                                             'servers': ['prod-1'],
                                             'template_variables': {'service_dir': '/data/bin/crypto-trader/strategy',
                                                                    'service_name': 'strategy',
                                                                    'update_script': './updatebin.sh',
                                                                    'pm2_name': 'strategy',
                                                                    'server_keywords': ['strategy'],
                                                                    'servers_by_env': {}}},
                                            {'name': 'crypto-supplier',
                                             'display_name': 'Supplier',
                                             'template': 'generic_backend_direct',
                                             'servers': ['prod-1'],
                                             'template_variables': {'service_dir': '/data/bin/crypto-trader/supplier',
                                                                    'service_name': 'supplier',
                                                                    'update_script': './updatebin.sh',
                                                                    'pm2_name': 'supplier',
                                                                    'server_keywords': ['supplier'],
                                                                    'servers_by_env': {}}},
                                            {'name': 'crypto-system',
                                             'display_name': 'System',
                                             'template': 'generic_backend_direct',
                                             'servers': ['prod-1'],
                                             'template_variables': {'service_dir': '/data/bin/crypto-trader/system',
                                                                    'service_name': 'system',
                                                                    'update_script': './updatebin.sh',
                                                                    'pm2_name': 'system',
                                                                    'server_keywords': ['system',
                                                                                        'system',
                                                                                        'main',
                                                                                        'master',
                                                                                        '主节点',
                                                                                        '主'],
                                                                    'servers_by_env': {}}},
                                            {'name': 'crypto-trader',
                                             'display_name': 'Trader',
                                             'template': 'generic_backend_direct',
                                             'servers': ['prod-1'],
                                             'template_variables': {'service_dir': '/data/bin/crypto-trader/trader',
                                                                    'service_name': 'trader',
                                                                    'update_script': './updatebin.sh',
                                                                    'pm2_name': 'trader',
                                                                    'server_keywords': ['trader'],
                                                                    'servers_by_env': {}}},
                                            {'name': 'crypto-transaction',
                                             'display_name': 'Transaction',
                                             'template': 'generic_backend_direct',
                                             'servers': ['prod-1'],
                                             'template_variables': {'service_dir': '/data/bin/crypto-trader/transaction',
                                                                    'service_name': 'transaction',
                                                                    'update_script': './updatebin.sh',
                                                                    'pm2_name': 'transaction',
                                                                    'server_keywords': ['transaction'],
                                                                    'servers_by_env': {}}}],
                               'environments': {'prod': {'display_name': '线上环境',
                                                         'base_path': '/data/bin/crypto-trader',
                                                         'servers': [],
                                                         'variables': {'environment': 'prod'}},
                                                'test': {'display_name': '测试环境',
                                                         'base_path': '/data/bin/crypto-trader',
                                                         'servers': [],
                                                         'variables': {'environment': 'test'}}},
                               'variables': {'default_server_group': '量化',
                                             'prod_server_exclude_keywords': ['测试',
                                                                              'test',
                                                                              'dev',
                                                                              'qa',
                                                                              'stage',
                                                                              'staging',
                                                                              'uat'],
                                             'test_server_include_keywords': ['测试',
                                                                              'test',
                                                                              'dev',
                                                                              'qa',
                                                                              'stage',
                                                                              'staging',
                                                                              'uat']}},
             'insider': {'display_name': 'Insider 报表',
                         'servers': ['prod-1'],
                         'services': [{'name': 'insider-frontend',
                                       'display_name': '前端',
                                       'template': 'generic_frontend',
                                       'servers': ['prod-1'],
                                       'template_variables': {'deploy_path': '/data/www', 'update_script': './www.sh'}},
                                      {'name': 'insider-backend',
                                       'display_name': '后端',
                                       'template': 'generic_backend_direct',
                                       'servers': ['prod-1'],
                                       'template_variables': {'service_dir': '/data/bin/insider',
                                                              'service_name': 'server',
                                                              'update_script': 'pm2 restart insider',
                                                              'pm2_name': 'insider'}}]},
             'sleuther': {'display_name': 'Sleuther 风控',
                          'servers': ['prod-1'],
                          'services': [{'name': 'sleuther-frontend',
                                        'display_name': '前端',
                                        'template': 'generic_frontend',
                                        'servers': ['prod-1'],
                                        'template_variables': {'deploy_path': '/data/www',
                                                               'update_script': './www.sh'}},
                                       {'name': 'sleuther-backend',
                                        'display_name': '后端',
                                        'template': 'generic_backend_bluegreen',
                                        'servers': ['prod-1'],
                                        'template_variables': {'service_dir': '/data/bin/sleuther/core',
                                                               'service_name': 'sleuther',
                                                               'pm2_name': 'sleuther',
                                                               'caddy_config': '/etc/caddy/sleuther.conf',
                                                               'caddy_old_port': '8080',
                                                               'caddy_new_port': '8081'}}]},
             'bot-hub': {'display_name': 'Bot Hub 机器人',
                         'servers': ['prod-1'],
                         'services': [{'name': 'bot-hub-update',
                                       'display_name': '程序更新',
                                       'template': 'generic_backend_direct',
                                       'servers': ['prod-1'],
                                       'template_variables': {'service_dir': '/data/bin/bot-hub',
                                                              'service_name': 'core',
                                                              'update_script': 'pm2 restart bot-hub',
                                                              'pm2_name': 'bot-hub'}}]},
             'dovo': {'display_name': 'Dovo',
                      'strategy': 'DOVO',
                      'description': 'Dovo 多区域部署系统，每个区域独立蓝绿发布',
                      'groups': {'pak': {'display_name': 'PAK 巴基斯坦',
                                         'server': 'pak-tecx',
                                         'base_path': '/data/bin/ata',
                                         'instances': ['pak1', 'pak2'],
                                         'global_config_path': '/data/bin/ata/config/global.yml',
                                         'update_script': 'bash ./binupdate.sh',
                                         'switch_script': 'bash ./portupdate.sh',
                                         'wait_after_update': 10},
                                 'tha': {'display_name': 'THA 泰国',
                                         'server': 'tha-aliyun',
                                         'base_path': '/data/bin/ata',
                                         'instances': ['tha1', 'tha2'],
                                         'global_config_path': '/data/bin/ata/config/global.yml',
                                         'update_script': 'bash ./binupdate.sh',
                                         'switch_script': 'bash ./portupdate.sh',
                                         'wait_after_update': 10},
                                 'idn': {'display_name': 'IDN 印尼',
                                         'server': 'idn-1xbet',
                                         'base_path': '/data/bin/ata',
                                         'instances': ['idn1', 'idn2'],
                                         'global_config_path': '/data/bin/ata/config/global.yml',
                                         'update_script': 'bash ./binupdate.sh',
                                         'switch_script': 'bash ./portupdate.sh',
                                         'wait_after_update': 10},
                                 'bgd': {'display_name': 'BGD 孟加拉',
                                         'server': 'bgd-server',
                                         'base_path': '/data/bin/ata',
                                         'instances': ['bgd1', 'bgd2'],
                                         'global_config_path': '/data/bin/ata/config/global.yml',
                                         'update_script': 'bash ./binupdate.sh',
                                         'switch_script': 'bash ./portupdate.sh',
                                         'wait_after_update': 10}}}},
 'settings': {'release_retention': {'deploy_keep_days': 90,
                                    'deploy_keep_max': 1000,
                                    'audit_keep_days': 180,
                                    'audit_keep_max': 5000,
                                    'keep_failed_days': 180,
                                    'dry_run': True,
                                    'deploy_success_keep_days': 90,
                                    'deploy_prod_success_keep_days': 180,
                                    'deploy_failed_keep_days': 180,
                                    'deploy_canceled_keep_days': 90,
                                    'deploy_rollback_keep_days': 365,
                                    'deploy_running_keep_hours': 72,
                                    'audit_high_risk_keep_days': 365,
                                    'tool_call_keep_days': 180,
                                    'tool_call_keep_max': 10000,
                                    'tool_plan_keep_days': 180,
                                    'tool_plan_keep_max': 5000,
                                    'keep_prod_failed_days': 365,
                                    'min_keep_days': 7},
              'notification_settings': {'enabled': False,
                                        'webhook_urls': [],
                                        'events': ['deploy.success',
                                                   'deploy.failed',
                                                   'deploy.canceled',
                                                   'rollback.success',
                                                   'rollback.failed'],
                                        'timeout': 5},
              'package_retention': {'package_keep_days': 90,
                                    'package_keep_max': 500,
                                    'test_success_keep_days': 60,
                                    'prod_success_keep_days': 180,
                                    'failed_package_keep_days': 180,
                                    'rollback_package_keep_days': 365,
                                    'unused_package_keep_days': 30,
                                    'keep_latest_success_per_service': 3,
                                    'keep_latest_prod_success_per_service': 5,
                                    'min_keep_days': 7,
                                    'protect_running_deployments': True,
                                    'protect_failed_deployments': True,
                                    'protect_rollback_candidates': True,
                                    'keep_metadata_after_file_delete': True,
                                    'max_upload_size_mb': 1024,
                                    'allowed_extensions': ['.tar.gz',
                                                           '.tgz',
                                                           '.tar',
                                                           '.zip',
                                                           '.jar',
                                                           '.war',
                                                           '.gz',
                                                           '.bin'],
                                    'dry_run': True}},
 'capability_server': {'enabled': True,
                       'http_tools_enabled': True,
                       'mcp_enabled': False,
                       'read_only': True,
                       'allow_deploy_plan': True,
                       'allow_deploy_execute': False,
                       'allow_prod_deploy': False,
                       'allow_config_write': False,
                       'allow_server_read': False,
                       'allow_server_write': False,
                       'require_confirmation': True,
                       'strict_prod_confirmation': True,
                       'token_expire_days': 90,
                       'allow_rollback': False,
                       'allow_package_write': False,
                       'allow_package_cleanup': False}}
