from __future__ import annotations

import base64
import hashlib
import logging
import os
from typing import Optional

from app.core.secrets_policy import STATUS_OK, classify_secret, is_production, rotate_hint

_PREFIX = "fernet:"
logger = logging.getLogger(__name__)
_insecure_key_warned = False


def is_encrypted(value: Optional[str]) -> bool:
    return bool(value and value.startswith(_PREFIX))


def _is_production() -> bool:
    return is_production()


def _normalize_fernet_key(raw_key: str) -> bytes:
    """Return a Fernet-compatible key.

    OPS_SECRET_KEY may be either a native Fernet key generated by
    `Fernet.generate_key()` or a normal long local secret/passphrase.  Supporting
    both keeps small local deployments easy to operate while still encrypting
    secrets at rest when a key is configured.
    """
    from cryptography.fernet import Fernet

    key_bytes = raw_key.encode("utf-8")
    try:
        Fernet(key_bytes)
        return key_bytes
    except Exception:
        digest = hashlib.sha256(key_bytes).digest()
        return base64.urlsafe_b64encode(digest)


def _get_fernet():
    global _insecure_key_warned
    key = os.getenv("OPS_SECRET_KEY")
    if not key:
        return None
    if not _insecure_key_warned:
        _insecure_key_warned = True
        info = classify_secret(key, name="OPS_SECRET_KEY")
        if info["status"] != STATUS_OK:
            logger.error(
                "OPS_SECRET_KEY 不安全（%s，指纹 %s）：库内凭据加密不具备实际保护能力，"
                "请轮换后重启（scripts/rotate_secrets.py）。生成命令：%s",
                info["reason"],
                info["fingerprint"],
                rotate_hint(),
            )
    from cryptography.fernet import Fernet
    return Fernet(_normalize_fernet_key(key))


def encrypt_secret(value: Optional[str]) -> Optional[str]:
    if value is None or value == "":
        return value
    if is_encrypted(value):
        return value
    fernet = _get_fernet()
    if not fernet:
        if _is_production() or os.getenv("OPS_REQUIRE_SECRET_ENCRYPTION") == "true":
            raise RuntimeError("OPS_SECRET_KEY is required for encrypted secret storage")
        if os.getenv("OPS_ALLOW_PLAINTEXT_SECRETS", "true").lower() in ("1", "true", "yes"):
            logger.warning("OPS_SECRET_KEY is not set; storing secret in plaintext for local development")
            return value
        raise RuntimeError("Secret encryption disabled and plaintext fallback is not allowed")
    return _PREFIX + fernet.encrypt(value.encode("utf-8")).decode("utf-8")


def decrypt_secret(value: Optional[str]) -> str:
    if not value:
        return ""
    if not is_encrypted(value):
        return value
    fernet = _get_fernet()
    if not fernet:
        raise RuntimeError("OPS_SECRET_KEY is required to decrypt stored secrets")
    return fernet.decrypt(value[len(_PREFIX):].encode("utf-8")).decode("utf-8")
